//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long UserID { get; set; }
        public long FeedTypeID { get; set; }
        public Nullable<long> JobID { get; set; }
        public Nullable<long> OtherUserID { get; set; }
    
        public virtual FeedType FeedType { get; set; }
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
