//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Feeds = new HashSet<Feed>();
            this.Messages = new HashSet<Message>();
            this.UserJobApplications = new HashSet<UserJobApplication>();
            this.UserJobFavorites = new HashSet<UserJobFavorite>();
            this.JobSkills = new HashSet<JobSkill>();
        }
    
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public long UserID { get; set; }
        public string Company { get; set; }
        public string LocationCity { get; set; }
        public string LocationState { get; set; }
        public string LocationCountry { get; set; }
        public string Industry { get; set; }
        public string Industry2 { get; set; }
        public string Title { get; set; }
        public string Responsibilities { get; set; }
        public string Qualifications { get; set; }
        public string EmployerIntroduction { get; set; }
        public string URL { get; set; }
        public string ShareURL { get; set; }
        public bool State { get; set; }
        public Nullable<long> ExperienceLevelType { get; set; }
    
        public virtual ICollection<Feed> Feeds { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<UserJobApplication> UserJobApplications { get; set; }
        public virtual ICollection<UserJobFavorite> UserJobFavorites { get; set; }
        public virtual ExperienceLevelType ExperienceLevelType1 { get; set; }
        public virtual ICollection<JobSkill> JobSkills { get; set; }
    }
}
