//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSkill
    {
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long JobID { get; set; }
        public string Skill { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
