//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long SenderID { get; set; }
        public long ReceiverID { get; set; }
        public bool State { get; set; }
        public string Message1 { get; set; }
        public string LinkURL { get; set; }
        public Nullable<long> LinkJobID { get; set; }
        public Nullable<long> LinkUserID { get; set; }
        public long MessageTypeID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
