//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public bool HasSent { get; set; }
        public string Error { get; set; }
        public string PushMessage { get; set; }
        public string DeviceToken { get; set; }
        public string SourceTable { get; set; }
        public string UserID { get; set; }
        public string JobID { get; set; }
    }
}
