//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Feeds = new HashSet<Feed>();
            this.Feeds1 = new HashSet<Feed>();
            this.Follows = new HashSet<Follow>();
            this.Follows1 = new HashSet<Follow>();
            this.Jobs = new HashSet<Job>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Messages2 = new HashSet<Message>();
            this.UserEducations = new HashSet<UserEducation>();
            this.UserEmployments = new HashSet<UserEmployment>();
            this.UserJobApplications = new HashSet<UserJobApplication>();
            this.UserJobFavorites = new HashSet<UserJobFavorite>();
            this.UserSkills = new HashSet<UserSkill>();
            this.UserEmploymentRecommendations = new HashSet<UserEmploymentRecommendation>();
        }
    
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LocationCity { get; set; }
        public string LocationState { get; set; }
        public string LocationCountry { get; set; }
        public string Industry { get; set; }
        public string Industry2 { get; set; }
        public string Summary { get; set; }
        public string PhotoURL { get; set; }
        public string LinkedInId { get; set; }
        public string DeviceToken { get; set; }
        public long ExperienceLevelType { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> TokenExpireTime { get; set; }
    
        public virtual ExperienceLevelType ExperienceLevelType1 { get; set; }
        public virtual ICollection<Feed> Feeds { get; set; }
        public virtual ICollection<Feed> Feeds1 { get; set; }
        public virtual ICollection<Follow> Follows { get; set; }
        public virtual ICollection<Follow> Follows1 { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ICollection<Message> Messages2 { get; set; }
        public virtual ICollection<UserEducation> UserEducations { get; set; }
        public virtual ICollection<UserEmployment> UserEmployments { get; set; }
        public virtual ICollection<UserJobApplication> UserJobApplications { get; set; }
        public virtual ICollection<UserJobFavorite> UserJobFavorites { get; set; }
        public virtual ICollection<UserSkill> UserSkills { get; set; }
        public virtual ICollection<UserEmploymentRecommendation> UserEmploymentRecommendations { get; set; }
    }
}
