//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEducation
    {
        public UserEducation()
        {
            this.UserEducationCourses = new HashSet<UserEducationCourse>();
        }
    
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public long UserID { get; set; }
        public string Name { get; set; }
        public string Degree { get; set; }
        public int StartYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public int StartMonth { get; set; }
        public Nullable<int> EndMonth { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<UserEducationCourse> UserEducationCourses { get; set; }
    }
}
